actions:
  - id: 1x1
    options:
      - id: strong hand
      - id: weak hand
      - id: shot
      - id: cut
  - id: fb
    options:
      - id: to
      - id: reb
      - id: make basket
  - id: put back
    options:
      - id: reg def
      - id: x all
  - id: w5
    options:
      - id: bh
      - id: roll
      - id: pop
      - id: out side
  - id: x all
    options:
      - id: outside
      - id: inside
  - id: off scr
  - id: w4
    options:
      - id: bh
      - id: roll
      - id: pop
      - id: out side
  - id: lp
    options:
      - id: 1x1
      - id: help
      - id: early post
  - id: zone
outcomes:
  - id: o2
    points: 2
    ended_in_shot: true
  - id: o3
    points: 3
    ended_in_shot: true
  - id: x2
    ended_in_shot: true
  - id: x3
    ended_in_shot: true
  - id: o2 + foul
    points: 2
    possible_free_throws: 1
    ended_in_shot: true
    statistic_tags:
      - foul
      - and one shooting foul
      - shooting foul
  - id: o3 + foul
    points: 3
    possible_free_throws: 1
    ended_in_shot: true
    statistic_tags:
      - foul
      - and one shooting foul
      - shooting foul
      - three point shoot foul
  - id: x2 + foul
    possible_free_throws: 2
    ended_in_shot: true
    statistic_tags:
      - foul
      - shooting foul
  - id: x3 + foul
    possible_free_throws: 3
    ended_in_shot: true
    statistic_tags:
      - foul
      - shooting foul
      - three point shoot foul
  - id: steal / to
  - id: bonus foul
    possible_free_throws: 3
    ended_in_shot: true
    statistic_tags:
      - foul
      - bonus foul
  - id: smart foul
    statistic_tags:
      - foul
      - smart foul
  - id: no bonus foul
    statistic_tags:
      - foul
      - no bonus foul
layouts:
  - name: Basic
    actions:
      - 1x1
      - fb
      - put back
      - w5
      - x all
      - off scr
      - w4
      - lp
      - zone
  - name: Detailed
    actions:
      - 1x1
      - fb
      - put back
      - tw5
      - x all
      - off scr
      - tw4
      - lp
      - zone
      - sw5
      - g to g
      - press
      - sw4
      - special situation
      - other
