name: build-bryant

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-push:
    uses: ./.github/workflows/build.yml
    with:
      binary: bryant
      latest_tag: ${{ github.event_name != 'pull_request' }}
