name: build

on:
  workflow_call:
    inputs:
      binary:
        required: true
        type: string
      repository:
        required: true
        type: string
      iam_role:
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and Push

    permissions:
      contents: read
      packages: write
      id-token: write

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: ${{ inputs.iam_role }}

      - name: Get Git tag
        id: extract_tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "Latest tag: $TAG"
          echo "version_tag=$TAG" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - uses: docker/setup-buildx-action@v3
        name: Setup Docker buildx

      - id: meta
        uses: docker/metadata-action@v5
        name: Setup image metadata
        with:
          images: |
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.repository }}
          tags: |
            ${{ env.version_tag }}
            latest

      - uses: docker/build-push-action@v4
        id: push
        name: Push to registry
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BINARY=${{ inputs.binary }}
            ARCH=amd64
            OS=linux
