name: build

on:
  workflow_call:
    inputs:
      binary:
        required: true
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and Push

    permissions:
      contents: read
      packages: write
      id-token: write

    defaults:
      run:
        shell: bash

    outputs:
      image: ${{ env.REGISTRY }}/sportsbydata/${{ inputs.binary }}/${{ github.sha }}

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Get Git tag
        id: extract_tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "Latest tag: $TAG"
          echo "version_tag=$TAG" >> $GITHUB_ENV

      - uses: docker/login-action@v3
        name: Login to Docker
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3
        name: Setup Docker buildx

      - id: meta
        uses: docker/metadata-action@v5
        name: Setup image metadata
        with:
          images: |
            ${{ env.REGISTRY }}/sportsbydata/${{ inputs.binary }}
          tags: |
            ${{ env.version_tag }}
            latest

      - uses: docker/build-push-action@v4
        id: push
        name: Push to registry
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BINARY=${{ inputs.binary }}
            ARCH=amd64
            OS=linux
