name: build-bryant

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-push:
    uses: ./.github/workflows/build.yml
    with:
      binary: bryant
      latest_tag: ${{ github.event_name != 'pull_request' }}
  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    name: Deploy

    defaults:
      run:
        shell: bash

    steps:
      - name: Invoke
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: .github/workflows/dev-bryant-deploy-ansible.yml
          repo: sportsbydata/infra
          inputs: '{ "image_tag": "${{ github.sha }}" }'
          token: "${{ secrets.EXEC_WORKFLOW_TOKEN }}"
