name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy

    defaults:
      run:
        shell: bash

    steps:
      - name: Invoke
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: .github/workflows/dev-bryant-deploy-ansible.yml
          repo: sportsbydata/infra
          inputs: '{ "env": "dev", "image_tag": "${{ github.sha }}" }'
          token: "${{ secrets.EXEC_WORKFLOW_TOKEN }}"
