name: deploy

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: "Name of environment"
        options:
          - dev

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: sportsbydata/bryant

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and Push

    permissions:
      contents: read
      packages: write
      id-token: write

    defaults:
      run:
        shell: bash

    outputs:
      image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ github.sha }}

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: docker/login-action@v3
        name: Login to Docker
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3
        name: Setup Docker buildx

      - id: meta
        uses: docker/metadata-action@v5
        name: Setup image metadata
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,enable=true,prefix=,format=long
            latest

      - uses: docker/build-push-action@v4
        id: push
        name: Push to registry
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BINARY=bryant
            ARCH=amd64
            OS=linux

      - name: Invoke workflow in another repo with inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: .github/workflows/bryant-deploy-ansible.yml
          repo: sportsbydata/infra
          inputs: '{ "env": "${{ github.event.inputs.env }}", "image_tag": "{{ github.sha }}" }'
          token: "${{ secrets.EXEC_WORKFLOW_TOKEN }}"
